# Site settings
title: Erika R. Ortiz
email: erikarortiz@gmail.com
url: https://erika-ortiz.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Machine Learning Engineer - Data Scientist - Philosopher "
meta_author: Erika Rita Ortiz

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  secondary: 253C59 #025959 #2c3e50  #FD6E8A #dark nav bar
  primary: 58788C #80B3FF 
  primary-rgb: "252,246,169" #"242,224,201" # box portfolio
  primary-bis: fcf6a9 #cffaf0 #F8D30 #about me
  secondary-dark: 233140 #A2122F
  terciary: 58788C #04BFBF # body

# Footer settings
footer:
  copyright: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
  location: email
  credits: Phone
  social: Social Media
  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/erika-r-ortiz/
  #- title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/Erika-Ortiz 

# Credits content
credits: '(+54) 9 351 2084173'

# Postal address (add as many lines as necessary)
address:
  - line: erikarortiz@gmail.com



# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
